#!/usr/bin/env node
/**
 * Mirrors `shared/wiki-image-strategy.ts` (source of truth) into both apps.
 *
 * Why we copy instead of symlinking or relying on `../shared` imports :
 *   - Backend Dockerfile does `COPY . .` from `backend/` only — anything
 *     outside that folder is invisible to the Docker build context.
 *   - Cloudflare Pages bundles each Function with esbuild from `frontend/`
 *     and relative imports stay safer when the file lives inside the bundle
 *     root.
 *   - Both `tsc --noEmit` and the test runners need the file present at a
 *     stable in-tree path so this script is wired as `prebuild` in each
 *     package.json AND the generated copies are committed (so dev / tests
 *     never see a missing file).
 *
 * Run :
 *   node scripts/sync-shared.cjs        # at repo root
 *   npm run build                       # auto-runs from each app's prebuild
 */

const fs = require('node:fs');
const path = require('node:path');

const REPO_ROOT = path.resolve(__dirname, '..');
const SOURCE = path.join(REPO_ROOT, 'shared', 'wiki-image-strategy.ts');

const TARGETS = [
  path.join(REPO_ROOT, 'backend', 'src', '_shared', 'wiki-image-strategy.ts'),
  path.join(REPO_ROOT, 'frontend', 'functions', '_shared', 'wiki-image-strategy.ts'),
];

if (!fs.existsSync(SOURCE)) {
  console.error(`[sync-shared] missing source ${SOURCE}`);
  process.exit(1);
}

const HEADER =
  '// AUTO-GENERATED — do NOT edit. Source of truth : shared/wiki-image-strategy.ts.\n' +
  '// Regenerated by scripts/sync-shared.cjs (wired via `prebuild` in package.json).\n\n';

const sourceContent = fs.readFileSync(SOURCE, 'utf8');
const stamped = HEADER + sourceContent;

for (const target of TARGETS) {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  // Write only when content differs to avoid polluting git status / mtime.
  let current = '';
  try {
    current = fs.readFileSync(target, 'utf8');
  } catch {
    current = '';
  }
  if (current !== stamped) {
    fs.writeFileSync(target, stamped);
    console.log(`[sync-shared] wrote ${path.relative(REPO_ROOT, target)}`);
  } else {
    console.log(`[sync-shared] up-to-date ${path.relative(REPO_ROOT, target)}`);
  }
}
